apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: wordpress:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "200m"      # Requête de CPU (200 milliCPU)
              memory: "512Mi"   # Requête de mémoire (512 MiB)
            limits:
              cpu: "500m"      # Limite de CPU (500 milliCPU)
              memory: "1Gi"    # Limite de mémoire (1 GiB)
          env:
            - name: WORDPRESS_DB_HOST
              value: database:3306
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: WORDPRESS_CONFIG_EXTRA
              value: |
                define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST'] . ':8081');
                define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST'] . ':8081');
            - name: WORDPRESS_DEBUG
              value: "1"

