apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-donnee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: base-donnee
  template:
    metadata:
      labels:
        app: base-donnee
    spec:
      containers:
        - name: base-donnee
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root_pass"
            - name: MYSQL_DATABASE
              value: "wordpress"
            - name: MYSQL_USER
              value: "wp_user"
            - name: MYSQL_PASSWORD
              value: "wp_pass"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: base-donnee
  labels:
    app: base-donnee
spec:
  selector:
    app: base-donnee
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi