apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: wordpress:latest
        ports:
        - containerPort: 8081  # Changé de 80 à 8081
        env:
        - name: WORDPRESS_CONFIG_EXTRA
          value: |
            define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST'] . ':8081');
            define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST'] . ':8081');
