apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8081      # Port externe du Service
      targetPort: 8081  # Doit matcher containerPort