apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-exporter
  template:
    metadata:
      labels:
        app: wordpress-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9100"
    spec:
      containers:
      - name: wordpress-exporter
        image: prometheuscommunity/wordpress-exporter
        env:
        - name: WORDPRESS_URL
          value: "http://wordpress:80"
        - name: WORDPRESS_USER
          value: "admin"
        - name: WORDPRESS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: password
        ports:
        - containerPort: 9100
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-exporter
spec:
  selector:
    app: wordpress-exporter
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
      