all:
  children:
    k8s_masters:
      hosts:
        master01:
          ansible_host: "192.168.213.212"   # Remplacer par l'IP réelle du master
    #k8s_workers:
     # hosts:
      #  node01:
       #   ansible_host: "192.168.1.101"       # Remplacer par l'IP réelle du worker (backend)
       # database:
         # ansible_host: "192.168.1.102"       # Remplacer par l'IP réelle du worker pour la BDD
